name: MemoryWarning
main: com.webkonsept.bukkit.memorywarning.MemoryWarning
version: 0.1
website: http://minecraft.webkonsept.com/
author: Fredrik Vold
database: false
description: >
        Get a warning when the server is about to run out of memory, and try to do something about it.
commands:
    memorywarning:
        aliases:
        description: Interact with the MemoryWarning plugin
        usage: /<command> [poll|setlevel level value]
